export const [
  CN,
  EN,
  DE,
  ES,
  PT_BR,
  JA,
  TR
] = ['cn', 'en', 'de', 'es', 'pt-br', 'ja', 'tr']

export default {
  // 中文
  [CN]: {
    addButton: '添加按钮',
    addTitle: '添加区域',
    delButton: '删除按钮',
    delTitle: '删除区域',
    next: '下一页',
    nextTitle: '下 page_size (→)',
    previous: '上一页',
    previousTitle: '上 page_size (←)',
    firstTitle: '首页 (Shift + ←)',
    lastTitle: '尾页 (Shift + →)',
    getAllButtons: '获得全部 (↓)',
    getAllAlt: '(按钮)',
    closeButton: '关闭 (Tab键)',
    closeAlt: '(按钮)',
    loading: '读取中...',
    loadingAlt: '(读取中)',
    pageInfo: '第 page_num 页(共page_count页)',
    selectNg: '请注意：请从列表中选择.',
    selectOk: 'OK : 已经选择.',
    notFound: '无查询结果',
    ajaxError: '连接到服务器时发生错误！',
    clear: '清除内容',
    selectAll: '选择当前页项目',
    UnSelectAll: '取消选择当前页项目',
    clearAll: '清除全部已选择项目',
    maxSelected: '最多只能选择 max_selected_limit 个项目'
  },
  // English
  [EN]: {
    addButton: 'Add button',
    addTitle: 'add a box',
    delButton: 'Del button',
    delTitle: 'delete a box',
    next: 'Next',
    nextTitle: 'Next page_size (Right key)',
    previous: 'Previous',
    previousTitle: 'Previous page_size (Left key)',
    firstTitle: 'First (Shift + Left key)',
    lastTitle: 'Last (Shift + Right key)',
    getAllButtons: 'Get All (Down key)',
    getAllAlt: '(button)',
    closeButton: 'Close (Tab key)',
    closeAlt: '(button)',
    loading: 'loading...',
    loadingAlt: '(loading)',
    pageInfo: 'Page page_num of page_count',
    selectNg: 'Attention : Please choose from among the list.',
    selectOk: 'OK : Correctly selected.',
    notFound: 'not found',
    ajaxError: 'An error occurred while connecting to server.',
    clear: 'Clear content',
    selectAll: 'Select current page',
    UnSelectAll: 'Clear current page',
    clearAll: 'Clear all selected',
    maxSelected: 'You can only select up to max_selected_limit items'
  },
  // German
  [DE]: {
    addButton: 'Hinzufügen-Button',
    addTitle: 'Box hinzufügen',
    delButton: 'Löschen-Button',
    delTitle: 'Box löschen',
    next: 'Nächsten',
    nextTitle: 'Nächsten page_size (Pfeil-rechts)',
    previous: 'Vorherigen',
    previousTitle: 'Vorherigen page_size (Pfeil-links)',
    firstTitle: 'Ersten (Umschalt + Pfeil-links)',
    lastTitle: 'Letzten (Umschalt + Pfeil-rechts)',
    getAllButtons: 'alle (Pfeil-runter)',
    getAllAlt: '(Button)',
    closeButton: 'Schließen (Tab)',
    closeAlt: '(Button)',
    loading: 'lade...',
    loadingAlt: '(lade)',
    pageInfo: 'page_num von page_count',
    selectNg: 'Achtung: Bitte wählen Sie aus der Liste aus.',
    selectOk: 'OK : Richtig ausgewählt.',
    notFound: 'nicht gefunden',
    ajaxError: 'Bei der Verbindung zum Server ist ein Fehler aufgetreten.',
    clear: 'Löschen Sie den Inhalt',
    selectAll: 'Wähle diese Seite',
    UnSelectAll: 'Diese Seite entfernen',
    clearAll: 'Alles löschen',
    maxSelected: 'Sie können nur bis zu max_selected_limit Elemente auswählen'
  },
  // Spanish
  [ES]: {
    addButton: 'Agregar boton',
    addTitle: 'Agregar una opcion',
    delButton: 'Borrar boton',
    delTitle: 'Borrar una opcion',
    next: 'Siguiente',
    nextTitle: 'Proximas page_size (tecla derecha)',
    previous: 'Anterior',
    previousTitle: 'Anteriores page_size (tecla izquierda)',
    firstTitle: 'Primera (Shift + Left)',
    lastTitle: 'Ultima (Shift + Right)',
    getAllButtons: 'Ver todos (tecla abajo)',
    getAllAlt: '(boton)',
    closeButton: 'Cerrar (tecla TAB)',
    closeAlt: '(boton)',
    loading: 'Cargando...',
    loadingAlt: '(Cargando)',
    pageInfo: 'page_num de page_count',
    selectNg: 'Atencion: Elija una opcion de la lista.',
    selectOk: 'OK: Correctamente seleccionado.',
    notFound: 'no encuentre',
    ajaxError: 'Un error ocurrió mientras conectando al servidor.',
    clear: 'Borrar el contenido',
    selectAll: 'Elija esta página',
    UnSelectAll: 'Borrar esta página',
    clearAll: 'Borrar todo marcado',
    maxSelected: 'Solo puedes seleccionar hasta max_selected_limit elementos'
  },
  // Brazilian Portuguese
  [PT_BR]: {
    addButton: 'Adicionar botão',
    addTitle: 'Adicionar uma caixa',
    delButton: 'Apagar botão',
    delTitle: 'Apagar uma caixa',
    next: 'Próxima',
    nextTitle: 'Próxima page_size (tecla direita)',
    previous: 'Anterior',
    previousTitle: 'Anterior page_size (tecla esquerda)',
    firstTitle: 'Primeira (Shift + Left)',
    lastTitle: 'Última (Shift + Right)',
    getAllButtons: 'Ver todos (Seta para baixo)',
    getAllAlt: '(botão)',
    closeButton: 'Fechar (tecla TAB)',
    closeAlt: '(botão)',
    loading: 'Carregando...',
    loadingAlt: '(Carregando)',
    pageInfo: 'page_num de page_count',
    selectNg: 'Atenção: Escolha uma opção da lista.',
    selectOk: 'OK: Selecionado Corretamente.',
    notFound: 'não encontrado',
    ajaxError: 'Um erro aconteceu enquanto conectando a servidor.',
    clear: 'Limpe o conteúdo',
    selectAll: 'Selecione a página atual',
    UnSelectAll: 'Remova a página atual',
    clearAll: 'Limpar tudo',
    maxSelected: 'Você só pode selecionar até max_selected_limit itens'
  },
  // Japanese
  [JA]: {
    addButton: '追加ボタン',
    addTitle: '入力ボックスを追加します',
    delButton: '削除ボタン',
    delTitle: '入力ボックスを削除します',
    next: '次へ',
    nextTitle: '次の page_size 件 (右キー)',
    previous: '前へ',
    previousTitle: '前の page_size 件 (左キー)',
    firstTitle: '最初のページへ (Shift + 左キー)',
    lastTitle: '最後のページへ (Shift + 右キー)',
    getAllButtons: '全件取得 (下キー)',
    getAllAlt: '画像:ボタン',
    closeButton: '閉じる (Tabキー)',
    closeAlt: '画像:ボタン',
    loading: '読み込み中...',
    loadingAlt: '画像:読み込み中...',
    pageInfo: 'page_num 件 (全 page_count 件)',
    selectNg: '注意 : リストの中から選択してください',
    selectOk: 'OK : 正しく選択されました。',
    notFound: '(0 件)',
    ajaxError: 'サーバとの通信でエラーが発生しました。',
    clear: 'コンテンツをクリアする',
    selectAll: '当ページを選びます',
    UnSelectAll: '移して当ページを割ります',
    clearAll: '選択した項目をクリアする',
    maxSelected: '最多で max_selected_limit のプロジェクトを選ぶことしかできません'
  },
  // Turkish
  [TR]: {
    addButton: 'Buton ekle',
    addTitle: 'kutu ekle',
    delButton: 'Buton sil',
    delTitle: 'kutuyu sil',
    next: 'sonraki',
    nextTitle: 'Sonraki page_size (Sağ tuş)',
    previous: 'Önceki',
    previousTitle: 'Önceki page_size (Sol tuş)',
    firstTitle: 'İlk (Shift + Sol tuş)',
    lastTitle: 'Son (Shift + Sağ tuş)',
    getAllButton: 'Tümünü Al (Alt tuş)',
    getAllAlt: '(button)',
    closeButton: 'kapat (Tab düğmesi)',
    closeAlt: '(buton)',
    loading: 'yükleniyor...',
    loadingAlt: '(yükleniyor)',
    pageInfo: 'Sayfa page_num / page_count',
    selectNg: 'Uyarı: Lütfen listeden seçim yapın.',
    selectOk: 'Tamam: Doğru seçildi.',
    notFound: 'bulunamadı',
    ajaxError: 'Sunucuya bağlanırken bir hata meydana geldi.',
    clear: 'İçeriği temizle',
    selectAll: 'Mevcut sayfayı seç',
    unSelectAll: 'Mevcut sayfayı temizle',
    clearAll: 'Seçili olanları temizle',
    maxSelected: 'Yalnızca en fazla max_selected_limit öğe seçebilirsiniz'
  }
}
